miasto(wrocław, polska).
miasto(warszawa, polska).
miasto(kraków, polska).
miasto(berlin, niemcy).
miasto(monachium, niemcy).
miasto(paryż, francja).
miasto(lima, peru).
miasto(cusco, peru).
panstwo(polska, europa).
panstwo(niemcy, europa).
panstwo(francja, europa).
panstwo(peru, ameryka).
